### ISSUE TITLE
Sort papers by category

### ISSUE THREAD

**Issue by DCtheTall** [ybayle/awesome-deep-learning-music#19]
Right now, the list of _all_ academic papers on DL4M is currently listed in order of publish date.

While the collection of papers is great, I think the list may benefit by some sort of organization by topic? Some examples of topics to sort by might be genre classification (or more generally, audio tagging), music feature extraction, generative models, or recommendation models. It could also be nice to sort by model architecture type (e.g. DNN vs LSTM vs ConvNet).

If the owners of this repo are interested and can come to consensus on the paper topics, I'd be happy to supply a PR if needed 😄

**Comment by bayle42** [comment]
Hi @DCtheTall! Thanks for your interest in this project!
Do you think this https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.tsv could be what you need? It's actually a spreadsheet that you can filter with whatever you want. Notably you can sort it using a given task (e.g. https://github.com/ybayle/awesome-deep-learning-music/blob/master/tasks.md) Maybe this is sufficient for your needs?

**Comment by DCtheTall** [comment]
Yep, that covers what I am looking for. Thanks!

**Comment by ybayle** [comment]
@DCtheTall ! Nice!
Thanks for closing the issue.
Additionally, if you'd like to contribute to the repo, you can follow the guidelines here: 
https://github.com/ybayle/awesome-deep-learning-music/blob/master/CONTRIBUTING.md 
and had the articles that you like and the scientist you follow. But if you need a starting point, some missing article are indicated in this issue:
https://github.com/ybayle/awesome-deep-learning-music/issues/5
Cheers,
Yann
