### ISSUE TITLE
[REQ] Add HyMPS' resources collection

### ISSUE THREAD

**Issue by MarcoRavich** [ybayle/awesome-deep-learning-music#23]
Hi there, great list of resources !

Please add my collection too:

[HyMPS project](https://forart.it/HyMPS) \ [AUDIO](https://github.com/FORARTfe/HyMPS#-) \ [AI-based projects](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-based.md#--)

Thanks in advance !

**Comment by ybayle** [comment]
Hi @MarcoRavich , 
Thanks for your interest in this repo!
Please follow this guideline https://github.com/ybayle/awesome-deep-learning-music/blob/master/CONTRIBUTING.md to add a link to what you think would help the community in the ReadMe or to add a reference to a scientific published article.
Have a nice day!

**Comment by MarcoRavich** [comment]
Thanks !
