### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [ybayle/awesome-deep-learning-music#9]
Hi. @ybayle I'm a graphic designer and an open source enthusiast. I wanna make contribution for your project, what do you think ?
![42413020-36c0e0ce-8242-11e8-86c6-a2589d5bfcab-1-1-1](https://user-images.githubusercontent.com/36124339/45017760-01297d00-b018-11e8-8e8b-80b624146d10.png)
Best regard. Mirza Zulfan

**Comment by ybayle** [comment]
Hi @mirzazulfan and thank you very much for your proposition! I really like your red logo and I will add it to the repo!
Best

**Comment by mirzazulfan** [comment]
Hi @ybayle  Thanks for accepting my proposal. I'm glad you liked it. You can download All file in [Gdrive](https://drive.google.com/drive/folders/1Z2F-ALlz_UzS5VveeH4X_n5vCqQQ2Nlt) 
![512 horizontal](https://user-images.githubusercontent.com/36124339/45152084-3beb0b00-b1fa-11e8-8035-36222dd8d9a9.png)

Best Regard. Mirza Zulfan
